using Friflo.Engine.ECS;
using Godot;

/// <summary>Per-chunk tree instance data generated by TreeSpawnSystem.</summary>
public struct ChunkTrees : IComponent
{
	/// <summary>World-space positions of trees.</summary>
	public Vector3[] Positions;
	/// <summary>Tree type per tree (parallel array).</summary>
	public TreeType[] Types;
	/// <summary>Deterministic seed per tree for variation (parallel array).</summary>
	public int[] Seeds;
	/// <summary>Number of trees in this chunk.</summary>
	public int Count;
}

/// <summary>Tracks the Godot MultiMeshInstance3D nodes used to render trees in a chunk.</summary>
public struct ChunkTreeMesh : IComponent
{
	/// <summary>Godot InstanceIds for each MultiMeshInstance3D (trunk + canopy per type).</summary>
	public ulong[] InstanceIds;
}
